### ISSUE TITLE
Missing frameworks for .NET

### ISSUE THREAD

**Issue by DragonEyeDesigns** [Hancapo/Folder2YTD#1]
When I try to run the .exe it gives me the error -To run this application, you must install the missing frameworks for .NET. Clicking yes takes me to the .NET 6.0 Runtime download page.. downloaded and installed it successfully, but the same error continues. I have also tried running as admin.

**Comment by Hancapo** [comment]
You have to download the x64 runtime.

**Comment by DragonEyeDesigns** [comment]
> You have to download the x64 runtime.

I did that. I guess it just flat out refuses to run on my system for some reason

**Comment by Hancapo** [comment]
you can also try to install the x86 one, but I don't think that's the issue, restart your PC and try again.

**Comment by DragonEyeDesigns** [comment]
> you can also try to install the x86 one, but I don't think that's the issue, restart your PC and try again.

I tried both installs of .NET and restarted. Nothing is helping.

**Comment by Hancapo** [comment]
You must be downloading the wrong thing

![image](https://user-images.githubusercontent.com/20731612/178088941-ab80cbe8-76fe-467f-b6e4-7a7de13e0b37.png)

**Comment by Hancapo** [comment]
I released a new version, check if this one works for you.

**Comment by DragonEyeDesigns** [comment]
The program starts now. I have not had the opportunity to do a full test yet.
I had to download this new update for Folders2YTD and also download the more recent version of .NET - I had 6.0.6 X64 and installing 6.0.7 X64 did the trick.
I'll reply again when I have the time to test converting some images.
Thanks a lot for your help!
